# Generated by Django 5.1.1 on 2024-09-24 13:22

import app.utils.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required 25 characters or fewer. Letters, digits and . _ only.', max_length=25, unique=True, validators=[app.utils.validators.UsernameValidator()])),
                ('email', models.EmailField(error_messages={'unique': 'Invalid email.'}, help_text='Required 50 characters or fewer. Letters, digits and @ . _ only.', max_length=50, unique=True, validators=[app.utils.validators.EmailValidator()])),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clear_cache', models.BooleanField(default=True)),
                ('hide_text', models.BooleanField(default=False)),
                ('mse', models.BooleanField(default=True)),
                ('ssim', models.BooleanField(default=True)),
                ('vgg16', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('uuid_reference', models.CharField(max_length=36)),
                ('uuid_compared', models.CharField(max_length=36)),
                ('method', models.CharField(choices=[('mse', 'Mean Squared Error (MSE)'), ('ssim', 'Structural Similarity Index (SSIM)'), ('vgg16', 'Neural Network vvgg VGG16')], max_length=5)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('is_similar', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('rar', 'RAR Archive'), ('zip', 'ZIP Archive'), ('png', 'PNG Image'), ('jpeg', 'JPEG Image')], max_length=5)),
                ('uuid', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
