# Generated by Django 4.2 on 2023-04-23 09:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfile_name_uploadedfile_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedaub_text', models.BooleanField(default=False)),
                ('clear_local_cache', models.BooleanField(default=True)),
                ('mse_comparator', models.BooleanField(default=True)),
                ('ssim_comparator', models.BooleanField(default=True)),
                ('vgg16_comparator', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=None, upload_to=app.models.get_upload_to),
        ),
    ]
