# Generated by Django 4.2 on 2023-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectsettings_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
