# Generated by Django 4.1.7 on 2023-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC_dialog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
